GET http://localhost:8081/statusHeroi

# GET http://localhost:8081/statusMonstro

# POST http://localhost:8081/atacar
# Content-Type: application/json

# {
# }

# POST http://localhost:8081/curar
# Content-Type: application/json

# {
# }